apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-data # Sets PV's name
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/nasir/odoo-assets/pv-storage # Sets the volume's path
  #persistentVolumeReclaimPolicy: Recycle
  
  #mountOptions:
   # - hard
   # - nfsvers=4.1
  #nfs:
   # path: /tmp
   # server: 172.17.0.2
